apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: events-api-network-delay
  namespace: ab-calicritters
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - ab-calicritters
    labelSelectors:
      app: events-api
      track: stable
  delay:
    latency: "300ms"
    jitter: "50ms"
    correlation: "25"
  direction: to
  duration: "90s"

