apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: assignment-api-pod-kill
  namespace: ab-calicritters
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - ab-calicritters
    labelSelectors:
      app: assignment-api
  duration: "60s"
